server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
